# Generated by Django 5.0.4 on 2024-05-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_timestamp', models.DateTimeField()),
                ('record_type', models.IntegerField()),
                ('glucose_history', models.IntegerField(blank=True, null=True)),
                ('glucose_scan', models.IntegerField(blank=True, null=True)),
                ('non_numeric_rapid_acting_insulin', models.CharField(blank=True, max_length=255, null=True)),
                ('rapid_acting_insulin', models.IntegerField(blank=True, null=True)),
                ('non_numeric_food_data', models.CharField(blank=True, max_length=255, null=True)),
                ('carbohydrates_grams', models.IntegerField(blank=True, null=True)),
                ('carbohydrates_portions', models.IntegerField(blank=True, null=True)),
                ('non_numeric_depot_insulin', models.CharField(blank=True, max_length=255, null=True)),
                ('depot_insulin', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('glucose_test_strips', models.IntegerField(blank=True, null=True)),
                ('ketone', models.IntegerField(blank=True, null=True)),
                ('meal_insulin', models.IntegerField(blank=True, null=True)),
                ('corrective_insulin', models.IntegerField(blank=True, null=True)),
                ('insulin_change_by_user', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
